version: "2.0"

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: "wurstmeister/kafka:0.11.0.1"
    ports:
     - "9092:9092"
    hostname: kafka
    links:
     - zookeeper
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=localhost
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_PORT=9092
